language: go
go:
    - '1.13'
install:
    - go get -v github.com/mattn/goveralls
    - make install
script:
    - make test
    - make cover-merge
    - goveralls -coverprofile=./gosip.full.coverprofile -service=travis-ci
