language: go
go:
  - '1.10'
install:
  - go get github.com/mattn/goveralls
  - make install
script:
  - make test
  - make cover-merge
  - goveralls -coverprofile=./gosip.full.coverprofile -service=travis-ci
branches:
  only:
    - master
    - dev
    - develop
